### ISSUE TITLE
Version 0.17 - Overview

### ISSUE THREAD

**Issue by Dorbedo** [Brig13Team/Operation_Kerberos#79]
- [x] general stuff
  - [x] code #66 #77 
  - [x] stringtable #7 #83
  - [x] new base #85 
  - [x] readme #83
  - [ ] changelog
  - [x] author update
- [x] headquater
  - [x] fdc #67 
  - [x] drones #69 
  - [x] logic
- [x] missions
  - [x] missionframework
  - [ ] mainmissions #68 
  - [x] secure informations bug #78 
  - [x] secondary objectives
- [ ] spawn
  - [x] fnc_macro_exec3d #87 
  - [x] groups config #81 #82
  - [x] gear config #86
  - [x] patrols
  - [x] strikeforce
  - [x] defence
  - [x] additional defence macros #84
  - [ ] marine patrols rewrite
- [x] logistics #60 
  - [x] unloadpoint
  - [x] missing config entries
  - [x] weight
  - [x] dialog progressbar
  - [x] ~~towing~~
- [x] TFAR
  - [x] enemy can hear you talking
  - [x] disable TFAR if EMP was launched

**Comment by Dorbedo** [comment]
removed some tasks

**Comment by Dorbedo** [comment]
#136 needs some more testing before closing this issue
